apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recruiting-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/dev-recruiters
  newName: devlaunchers/dev-recruiters
  newTag: "23ce451-202208032054" # {"$imagepolicy": "recruiting-staging:recruiting:tag"}
