apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recruiting-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/dev-recruiters
  newName: devlaunchers/dev-recruiters
  newTag: "868c195-202206281457" # {"$imagepolicy": "recruiting-staging:recruiting:tag"}
