apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recruiting-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/dev-recruiters
  newName: devlaunchers/dev-recruiters
  newTag: "8f936b6-202206101000" # {"$imagepolicy": "recruiting-staging:dev-recruiters:tag"}
